import '../models/models.dart';

abstract final class EvidenceCatalog {
  static final reviewedAt = DateTime(2026, 9, 28);

  static final references = <EvidenceReference>[
    EvidenceReference(
      id: 'soap-platelets-2021',
      group: 'Segurança',
      authors: 'Bauer et al. / SOAP',
      title: 'Interdisciplinary Consensus Statement on Neuraxial Procedures in Obstetric Patients With Thrombocytopenia',
      source: 'Anesthesia & Analgesia / SOAP',
      year: 2021,
      doi: '10.1213/ANE.0000000000005355',
      pmid: '33861047',
      url: 'https://www.soap.org/assets/docs/Consensus/SOAP%20Consensus%20Statement%20Thrombocytopenia%202021.pdf',
      population: 'Pacientes obstétricas com plaquetopenia.',
      notes: 'Decisão depende de etiologia, tendência, sangramento, DIC e riscos concorrentes.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'asra-antithrombotic-2025',
      group: 'Anticoagulação',
      authors: 'Kopp et al. / ASRA Pain Medicine',
      title: 'Regional anesthesia in the patient receiving antithrombotic or thrombolytic therapy: fifth edition',
      source: 'Regional Anesthesia & Pain Medicine',
      year: 2025,
      doi: '10.1136/rapm-2024-105766',
      pmid: '39880411',
      url: 'https://rapm.bmj.com/content/early/2025/10/16/rapm-2024-105766',
      population: 'Pacientes em uso de agentes antitrombóticos submetidos a procedimentos neuroaxiais.',
      notes: 'O aplicativo identifica a recomendação como ASRA; não mescla sociedades.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'soap-erac-2021',
      group: 'Raquianestesia',
      authors: 'Bollag et al. / SOAP',
      title: 'Enhanced Recovery After Cesarean Delivery Consensus Statement',
      source: 'Anesthesia & Analgesia',
      year: 2021,
      doi: '10.1213/ANE.0000000000005257',
      pmid: '33177330',
      url: 'https://www.soap.org/assets/docs/Society_for_Obstetric_Anesthesia_and_Perinatology_.95413.pdf',
      population: 'Cesárea com via neuroaxial em programa ERAC.',
      notes: 'Exemplo de opioide de longa ação: morfina IT 50–150 mcg; não é cálculo individual de dose.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'li-fentanyl-2025',
      group: 'Raquianestesia',
      authors: 'Li et al.',
      title: 'Efficacy of fentanyl combined with bupivacaine and morphine for spinal anesthesia during cesarean section',
      source: 'Journal of International Medical Research',
      year: 2025,
      doi: '10.1177/03000605251389749',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12589784/',
      population: '180 gestantes em cesárea eletiva; ensaio randomizado.',
      notes: 'Protocolo estudado: bupivacaína 10 mg + morfina 100 mcg; fentanil 10–15 mcg apresentou início mais rápido. Generalização limitada.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'asra-last-2020',
      group: 'Emergências',
      authors: 'Neal et al. / ASRA Pain Medicine',
      title: 'Checklist for Treatment of Local Anesthetic Systemic Toxicity',
      source: 'ASRA Pain Medicine',
      year: 2020,
      url: 'https://asra.com/news-publications/asra-updates/blog-landing/guidelines/2020/11/01/checklist-for-treatment-of-local-anesthetic-systemic-toxicity',
      population: 'Pacientes com suspeita de toxicidade sistêmica por anestésico local.',
      notes: 'Checklist em revisão; atualização esperada pela ASRA em 2027.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'who-pph-2025',
      group: 'Emergências',
      authors: 'WHO, FIGO e ICM',
      title: 'Consolidated guidelines for the prevention, diagnosis and treatment of postpartum haemorrhage',
      source: 'World Health Organization',
      year: 2025,
      url: 'https://www.who.int/publications/i/item/9789240115637',
      population: 'Hemorragia pós-parto após parto vaginal ou cesárea.',
      notes: 'Bundle de primeira resposta e escalonamento; adaptar ao protocolo institucional.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'oaa-das-airway-2015',
      group: 'Emergências',
      authors: 'Mushambi et al. / OAA-DAS',
      title: 'Guidelines for the management of difficult and failed tracheal intubation in obstetrics',
      source: 'Anaesthesia',
      year: 2015,
      doi: '10.1111/anae.13260',
      pmid: '26449292',
      url: 'https://das.uk.com/guidelines/obstetric_airway_guidelines_2015/',
      population: 'Anestesia geral obstétrica com intubação difícil ou falha.',
      notes: 'Algoritmo obstétrico específico; usar a versão institucional disponível.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'aha-pregnancy-arrest-2025',
      group: 'Emergências',
      authors: 'American Heart Association',
      title: 'Cardiac Arrest in Pregnancy Algorithm',
      source: '2025 AHA Guidelines for CPR and ECC',
      year: 2025,
      url: 'https://cpr.heart.org/-/media/CPR-Files/CPR-Guidelines-Files/2025-Algorithms/Algorithm-SC-ACLS-CA-in-Pregnancy-250620.pdf',
      population: 'Parada cardiorrespiratória na gestação.',
      notes: 'Deslocamento uterino contínuo; preparar parto ressuscitativo quando fundo uterino ≥ umbigo; meta de nascimento até 5 min sem ROSC.',
      lastReviewed: reviewedAt,
    ),
  ];

  static const matrix = <EvidenceMatrixRow>[
    EvidenceMatrixRow(
      variable: 'Plaquetas e neuroeixo',
      population: 'Plaquetopenia gestacional, ITP ou doença hipertensiva; sem outros fatores',
      medication: '—',
      technique: 'Raqui, peridural, CSE, DPE ou retirada de cateter',
      exposure: '≥70.000/mm³',
      outcome: 'Risco de hematoma provavelmente muito baixo',
      estimate: 'Razoável proceder se clinicamente indicado',
      referenceId: 'soap-platelets-2021',
      year: 2021,
      notes: 'Classe IIa, C-LD. Avaliar sangramento/DIC e contexto.',
    ),
    EvidenceMatrixRow(
      variable: 'Opioide neuroaxial de longa ação',
      population: 'Cesárea em programa ERAC',
      medication: 'Morfina intratecal',
      technique: 'Raquianestesia/CSE',
      exposure: '50–150 mcg',
      outcome: 'Analgesia multimodal pós-cesárea',
      estimate: 'Faixa de exemplo do consenso',
      referenceId: 'soap-erac-2021',
      year: 2021,
      notes: 'Não constitui dose individual automática; considerar risco e monitorização.',
    ),
    EvidenceMatrixRow(
      variable: 'Adjuvante lipofílico',
      population: 'Cesárea eletiva; n=180',
      medication: 'Fentanil + bupivacaína + morfina',
      technique: 'Intratecal',
      exposure: 'Fentanil 10–15 mcg + bupivacaína 10 mg + morfina 100 mcg',
      outcome: 'Início sensitivo/motor mais rápido versus controle',
      estimate: 'Faixa estudada; sem conversão em dose ideal',
      referenceId: 'li-fentanyl-2025',
      year: 2025,
      notes: 'Ensaio único; população e protocolo devem ser exibidos no app.',
    ),
  ];

  static EvidenceReference byId(String id) => references.firstWhere((item) => item.id == id);
}
