import '../models/models.dart';

abstract final class EvidenceCatalog {
  static final reviewedAt = DateTime(2026, 9, 29);

  static final references = <EvidenceReference>[
    EvidenceReference(
      id: 'soap-platelets-2021',
      group: 'Segurança',
      authors: 'Bauer et al. / SOAP',
      title: 'Interdisciplinary Consensus Statement on Neuraxial Procedures in Obstetric Patients With Thrombocytopenia',
      source: 'Anesthesia & Analgesia / SOAP',
      year: 2021,
      doi: '10.1213/ANE.0000000000005355',
      pmid: '33861047',
      url: 'https://www.soap.org/assets/docs/Consensus/SOAP%20Consensus%20Statement%20Thrombocytopenia%202021.pdf',
      population: 'Pacientes obstétricas com plaquetopenia.',
      notes: 'Decisão depende de etiologia, tendência, sangramento, DIC e riscos concorrentes.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'asra-antithrombotic-2025',
      group: 'Anticoagulação',
      authors: 'Kopp et al. / ASRA Pain Medicine',
      title: 'Regional anesthesia in the patient receiving antithrombotic or thrombolytic therapy: fifth edition',
      source: 'Regional Anesthesia & Pain Medicine',
      year: 2025,
      doi: '10.1136/rapm-2024-105766',
      pmid: '39880411',
      url: 'https://rapm.bmj.com/content/early/2025/10/16/rapm-2024-105766',
      population: 'Pacientes em uso de agentes antitrombóticos submetidos a procedimentos neuroaxiais.',
      notes: 'O aplicativo identifica a recomendação como ASRA; não mescla sociedades.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'soap-erac-2021',
      group: 'Raquianestesia',
      authors: 'Bollag et al. / SOAP',
      title: 'Enhanced Recovery After Cesarean Delivery Consensus Statement',
      source: 'Anesthesia & Analgesia',
      year: 2021,
      doi: '10.1213/ANE.0000000000005257',
      pmid: '33177330',
      url: 'https://www.soap.org/assets/docs/Society_for_Obstetric_Anesthesia_and_Perinatology_.95413.pdf',
      population: 'Cesárea com via neuroaxial em programa ERAC.',
      notes: 'Exemplo de opioide de longa ação: morfina IT 50–150 mcg; não é cálculo individual de dose.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'li-fentanyl-2025',
      group: 'Raquianestesia',
      authors: 'Li et al.',
      title: 'Efficacy of fentanyl combined with bupivacaine and morphine for spinal anesthesia during cesarean section',
      source: 'Journal of International Medical Research',
      year: 2025,
      doi: '10.1177/03000605251389749',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12589784/',
      population: '180 gestantes em cesárea eletiva; ensaio randomizado.',
      notes: 'Protocolo estudado: bupivacaína 10 mg + morfina 100 mcg; fentanil 10–15 mcg apresentou início mais rápido. Generalização limitada.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'asra-last-2020',
      group: 'Emergências',
      authors: 'Neal et al. / ASRA Pain Medicine',
      title: 'Checklist for Treatment of Local Anesthetic Systemic Toxicity',
      source: 'ASRA Pain Medicine',
      year: 2020,
      url: 'https://asra.com/news-publications/asra-updates/blog-landing/guidelines/2020/11/01/checklist-for-treatment-of-local-anesthetic-systemic-toxicity',
      population: 'Pacientes com suspeita de toxicidade sistêmica por anestésico local.',
      notes: 'Checklist em revisão; atualização esperada pela ASRA em 2027.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'who-pph-2025',
      group: 'Emergências',
      authors: 'WHO, FIGO e ICM',
      title: 'Consolidated guidelines for the prevention, diagnosis and treatment of postpartum haemorrhage',
      source: 'World Health Organization',
      year: 2025,
      url: 'https://www.who.int/publications/i/item/9789240115637',
      population: 'Hemorragia pós-parto após parto vaginal ou cesárea.',
      notes: 'Bundle de primeira resposta e escalonamento; adaptar ao protocolo institucional.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'oaa-das-airway-2015',
      group: 'Emergências',
      authors: 'Mushambi et al. / OAA-DAS',
      title: 'Guidelines for the management of difficult and failed tracheal intubation in obstetrics',
      source: 'Anaesthesia',
      year: 2015,
      doi: '10.1111/anae.13260',
      pmid: '26449292',
      url: 'https://das.uk.com/guidelines/obstetric_airway_guidelines_2015/',
      population: 'Anestesia geral obstétrica com intubação difícil ou falha.',
      notes: 'Algoritmo obstétrico específico; usar a versão institucional disponível.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'aha-pregnancy-arrest-2025',
      group: 'Emergências',
      authors: 'American Heart Association',
      title: 'Cardiac Arrest in Pregnancy Algorithm',
      source: '2025 AHA Guidelines for CPR and ECC',
      year: 2025,
      url: 'https://cpr.heart.org/-/media/CPR-Files/CPR-Guidelines-Files/2025-Algorithms/Algorithm-SC-ACLS-CA-in-Pregnancy-250620.pdf',
      population: 'Parada cardiorrespiratória na gestação.',
      notes: 'Deslocamento uterino contínuo; preparar parto ressuscitativo quando fundo uterino ≥ umbigo; meta de nascimento até 5 min sem ROSC.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'arzola-low-dose-2011',
      group: 'Raquianestesia',
      authors: 'Arzola e Wieczorek',
      title: 'Efficacy of low-dose bupivacaine in spinal anaesthesia for Caesarean delivery',
      source: 'British Journal of Anaesthesia',
      year: 2011,
      doi: '10.1093/bja/aer200',
      pmid: '21764820',
      url: 'https://pubmed.ncbi.nlm.nih.gov/21764820/',
      population: 'Cesárea eletiva; meta-análise de doses ≤8 mg versus >8 mg.',
      notes: 'Baixa dose reduziu hipotensão e náusea/vômito, mas aumentou suplementação intraoperatória.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'sng-baricity-2016',
      group: 'Raquianestesia',
      authors: 'Sng et al. / Cochrane',
      title: 'Hyperbaric versus isobaric bupivacaine for spinal anaesthesia for caesarean section',
      source: 'Cochrane Database of Systematic Reviews',
      year: 2016,
      doi: '10.1002/14651858.CD005143.pub3',
      pmid: '27629425',
      url: 'https://pubmed.ncbi.nlm.nih.gov/27629425/',
      population: 'Cesárea sob raquianestesia.',
      notes: 'Hiperbárica apresentou início mais rápido até T4; qualidade global da evidência baixa ou muito baixa para vários desfechos.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'onishi-bupivacaine-2017',
      group: 'Raquianestesia',
      authors: 'Onishi et al.',
      title: 'Optimal intrathecal hyperbaric bupivacaine dose with opioids for cesarean delivery',
      source: 'International Journal of Obstetric Anesthesia',
      year: 2017,
      doi: '10.1016/j.ijoa.2017.04.001',
      pmid: '28623089',
      url: 'https://pubmed.ncbi.nlm.nih.gov/28623089/',
      population: 'Cesárea eletiva com CSE; bupivacaína 6–12 mg + fentanil 15 mcg + morfina 75 mcg.',
      notes: 'ED50/ED95 para manutenção por 60 min: 6,0/12,6 mg; maior dose aumentou fenilefrina e náusea/vômito.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'alimian-bupivacaine-2017',
      group: 'Raquianestesia',
      authors: 'Alimian et al.',
      title: 'Different doses of intrathecal hyperbaric bupivacaine plus sufentanil for cesarean section',
      source: 'Anesthesiology and Pain Medicine',
      year: 2017,
      doi: '10.5812/aapm.14426',
      pmid: '29696121',
      url: 'https://brieflands.com/journals/aapm/articles/14426',
      population: 'Cesárea eletiva; bupivacaína hiperbárica 8, 9 ou 10 mg + sufentanil 2,5 mcg.',
      notes: 'Recuperação sensitiva média 110–116 min e motora 107–116 min; estudo único.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'carvalho-isobaric-2005',
      group: 'Raquianestesia',
      authors: 'Carvalho et al.',
      title: 'ED50 and ED95 of intrathecal isobaric bupivacaine with opioids for cesarean delivery',
      source: 'Anesthesiology',
      year: 2005,
      doi: '10.1097/00000542-200509000-00025',
      pmid: '16129987',
      url: 'https://pubmed.ncbi.nlm.nih.gov/16129987/',
      population: 'Cesárea eletiva com CSE; 5–12 mg + fentanil 10 mcg + morfina 200 mcg.',
      notes: 'ED50 7,25 mg; ED95 13 mg sob as condições específicas do estudo.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'khaw-ropivacaine-2001',
      group: 'Raquianestesia',
      authors: 'Khaw et al.',
      title: 'Spinal ropivacaine for cesarean section: a dose-finding study',
      source: 'Anesthesiology',
      year: 2001,
      doi: '10.1097/00000542-200112000-00011',
      pmid: '11748390',
      url: 'https://pubmed.ncbi.nlm.nih.gov/11748390/',
      population: 'Cesárea; ropivacaína intratecal simples 10, 15, 20 ou 25 mg.',
      notes: 'Sucesso aumentou com dose; duração sensitiva e motora foi dose-dependente.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'bidikar-levo-fentanyl-2017',
      group: 'Raquianestesia',
      authors: 'Bidikar et al.',
      title: 'Intrathecal levobupivacaine and levobupivacaine plus fentanyl for cesarean section',
      source: 'Anesthesia: Essays and Researches',
      year: 2017,
      doi: '10.4103/0259-1162.194540',
      pmid: '28663648',
      url: 'https://pubmed.ncbi.nlm.nih.gov/28663648/',
      population: 'Cesárea; levobupivacaína 10 mg versus 7,5 mg + fentanil 12,5 mcg.',
      notes: 'Fentanil permitiu menor dose de anestésico com bloqueio adequado e recuperação motora mais precoce.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'sharma-levo-ropi-2025',
      group: 'Raquianestesia',
      authors: 'Sharma et al.',
      title: 'Isobaric levobupivacaine versus ropivacaine with fentanyl for elective cesarean section',
      source: 'Cureus',
      year: 2025,
      doi: '10.7759/cureus.77895',
      pmid: '39897244',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11787768/',
      population: '60 cesáreas eletivas; 10 mg de levobupivacaína ou ropivacaína + fentanil 25 mcg.',
      notes: 'Estudo pequeno: levobupivacaína teve maior duração; ropivacaína, regressão motora mais precoce.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'uppal-fentanyl-2020',
      group: 'Raquianestesia',
      authors: 'Uppal et al.',
      title: 'Efficacy of Intrathecal Fentanyl for Cesarean Delivery',
      source: 'Anesthesia & Analgesia',
      year: 2020,
      doi: '10.1213/ANE.0000000000003975',
      pmid: '30633056',
      url: 'https://pubmed.ncbi.nlm.nih.gov/30633056/',
      population: '17 ensaios randomizados; 1.064 pacientes em cesárea.',
      notes: 'Menos suplementação; primeira analgesia +91 min em média; mais prurido; sem mudança consistente na latência sensitiva ou duração motora.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'dahlgren-opioids-1997',
      group: 'Raquianestesia',
      authors: 'Dahlgren et al.',
      title: 'Intrathecal sufentanil, fentanyl, or placebo added to bupivacaine for cesarean section',
      source: 'Anesthesia & Analgesia',
      year: 1997,
      pmid: '9390596',
      url: 'https://pubmed.ncbi.nlm.nih.gov/9390596/',
      population: 'Cesárea eletiva; sufentanil 2,5/5 mcg ou fentanil 10 mcg com bupivacaína.',
      notes: 'Opioides lipofílicos melhoraram a qualidade; sufentanil apresentou efeito mais prolongado.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'wilwerth-opioids-2016',
      group: 'Raquianestesia',
      authors: 'Wilwerth et al.',
      title: 'Spinal fentanyl versus sufentanil for postoperative analgesia after cesarean delivery',
      source: 'European Journal of Anaesthesiology',
      year: 2016,
      doi: '10.1097/EJA.0000000000000424',
      pmid: '27137756',
      url: 'https://pubmed.ncbi.nlm.nih.gov/27137756/',
      population: 'Cesárea; fentanil 25 mcg versus sufentanil 2,5 ou 5 mcg.',
      notes: 'Analgesia: 187 min com fentanil; 214–236 min com sufentanil, com ampla dispersão.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'prospect-cesarean-2026',
      group: 'Raquianestesia',
      authors: 'Crowe et al. / PROSPECT',
      title: 'Pain management after elective caesarean section under neuraxial anaesthesia',
      source: 'Anaesthesia',
      year: 2026,
      doi: '10.1111/anae.70141',
      pmid: '41693258',
      url: 'https://pubmed.ncbi.nlm.nih.gov/41693258/',
      population: 'Cesárea eletiva sob anestesia neuroaxial; revisão de 61 ensaios.',
      notes: 'Recomenda morfina intratecal 50–100 mcg no contexto de analgesia multimodal.',
      lastReviewed: reviewedAt,
    ),
    EvidenceReference(
      id: 'sultan-morphine-2016',
      group: 'Raquianestesia',
      authors: 'Sultan et al.',
      title: 'The Effect of Intrathecal Morphine Dose on Outcomes After Elective Cesarean Delivery',
      source: 'Anesthesia & Analgesia',
      year: 2016,
      doi: '10.1213/ANE.0000000000001255',
      pmid: '27089000',
      url: 'https://pubmed.ncbi.nlm.nih.gov/27089000/',
      population: '11 ensaios; 50–100 mcg versus >100–250 mcg.',
      notes: 'Dose maior prolongou analgesia em 4,49 h, mas aumentou prurido e vômitos.',
      lastReviewed: reviewedAt,
    ),
  ];

  static const matrix = <EvidenceMatrixRow>[
    EvidenceMatrixRow(
      variable: 'Plaquetas e neuroeixo',
      population: 'Plaquetopenia gestacional, ITP ou doença hipertensiva; sem outros fatores',
      medication: '—',
      technique: 'Raqui, peridural, CSE, DPE ou retirada de cateter',
      exposure: '≥70.000/mm³',
      outcome: 'Risco de hematoma provavelmente muito baixo',
      estimate: 'Razoável proceder se clinicamente indicado',
      referenceId: 'soap-platelets-2021',
      year: 2021,
      notes: 'Classe IIa, C-LD. Avaliar sangramento/DIC e contexto.',
    ),
    EvidenceMatrixRow(
      variable: 'Opioide neuroaxial de longa ação',
      population: 'Cesárea em programa ERAC',
      medication: 'Morfina intratecal',
      technique: 'Raquianestesia/CSE',
      exposure: '50–150 mcg',
      outcome: 'Analgesia multimodal pós-cesárea',
      estimate: 'Faixa de exemplo do consenso',
      referenceId: 'soap-erac-2021',
      year: 2021,
      notes: 'Não constitui dose individual automática; considerar risco e monitorização.',
    ),
    EvidenceMatrixRow(
      variable: 'Adjuvante lipofílico',
      population: 'Cesárea eletiva; n=180',
      medication: 'Fentanil + bupivacaína + morfina',
      technique: 'Intratecal',
      exposure: 'Fentanil 10–15 mcg + bupivacaína 10 mg + morfina 100 mcg',
      outcome: 'Início sensitivo/motor mais rápido versus controle',
      estimate: 'Faixa estudada; sem conversão em dose ideal',
      referenceId: 'li-fentanyl-2025',
      year: 2025,
      notes: 'Ensaio único; população e protocolo devem ser exibidos no app.',
    ),
    EvidenceMatrixRow(
      variable: 'Dose baixa de bupivacaína',
      population: 'Cesárea eletiva',
      medication: 'Bupivacaína intratecal',
      technique: 'Raquianestesia',
      exposure: '≤8 mg versus >8 mg',
      outcome: 'Hipotensão, náusea/vômito e necessidade de suplementação',
      estimate: 'Menos efeitos maternos, mas RR 3,76 para suplementação',
      referenceId: 'arzola-low-dose-2011',
      year: 2011,
      notes: 'Não usar a redução de dose como regra automática.',
    ),
    EvidenceMatrixRow(
      variable: 'Recuperação do bloqueio',
      population: 'Cesárea eletiva a termo',
      medication: 'Bupivacaína hiperbárica + sufentanil 2,5 mcg',
      technique: 'Raquianestesia',
      exposure: '8–10 mg',
      outcome: 'Recuperação sensitiva e motora',
      estimate: 'Médias entre 107 e 116 min',
      referenceId: 'alimian-bupivacaine-2017',
      year: 2017,
      notes: 'Faixa do app é alargada para refletir variabilidade; não é previsão individual.',
    ),
    EvidenceMatrixRow(
      variable: 'Fentanil intratecal',
      population: 'Cesárea',
      medication: 'Fentanil + bupivacaína',
      technique: 'Raquianestesia',
      exposure: 'Faixas variadas entre ensaios',
      outcome: 'Suplementação e primeiro resgate analgésico',
      estimate: 'RR 0,18 para suplementação; +91 min até analgesia',
      referenceId: 'uppal-fentanyl-2020',
      year: 2020,
      notes: 'Mais prurido; sem efeito consistente em latência sensitiva ou duração motora.',
    ),
    EvidenceMatrixRow(
      variable: 'Morfina intratecal',
      population: 'Cesárea eletiva',
      medication: 'Morfina',
      technique: 'Neuroaxial',
      exposure: '50–100 mcg',
      outcome: 'Analgesia pós-operatória',
      estimate: 'Faixa recomendada PROSPECT 2026',
      referenceId: 'prospect-cesarean-2026',
      year: 2026,
      notes: 'Doses maiores podem prolongar analgesia, com mais prurido e vômitos.',
    ),
  ];

  static EvidenceReference byId(String id) => references.firstWhere((item) => item.id == id);
}
